name: 'Publish Release Assets to Asset Transparency Log'

description: 'Verify assets in a GitHub release against the Asset Transparency Log'

outputs:
  verified: 
    description: 'List of verified URLs'
  failed: 
    description: 'List of failed URLs'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
    icon: 'download-cloud'  
    color: 'green'
